#Necesario para instalar cosas
sudo: required
dist: trusty
languaje: python	#El Tester esta hecho en python, lo tomamos como base
python:
- '2.7'
before install:
- "./install-dependencies.sh"	#instalamos dependencias de los demas lenguajes
#install:
before_script:
- "./buildProject.sh"	#compilamos todo lo que sea necesario
script: "./Tester/main.py"	#corremos pruebas
#after_success:
#after_failure:
before_deploy:
- "./before-deploy.sh"
deploy:
  provider: script
  script: "./deploy.sh"
after_deploy:
- "./after-deploy.sh"
#after_script: