#Necesario para instalar cosas
sudo: required
dist: trusty
language: python	#El Tester esta hecho en python, lo tomamos como base
#agregamos a la matrix gcc 4.9 y clang 3.7
gcc:
 - 4.9
clang:
 - 3.7
python:
  - '2.7'
before_install:
  - "sudo ./install-dependencies.sh"	#instalamos dependencias de los demas lenguajes
#install:
before_script:
  - "sudo ./buildProject.sh"	#compilamos todo lo que sea necesario
script: 
  - "sudo ./Tester/main.py"   #tests
#  - "sudo ./AppServer/UnitTest"   #no encuentra el test, posiblemente porque el lang es python
cache:
  pip: true
  directories: 
  - ./AppServer/lib	
#after_success:
#after_failure:
#before_deploy:
#deploy:
#after_deploy:
#after_script:
